services:
  - type: web
    name: kuhuu-fashion-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
